### ISSUE TITLE
pysonofflan discover: too any open files 

### ISSUE THREAD

**Issue by rgiordani71** [beveradb/pysonofflan#117]
* pySonoffLAN version: 0.3.0
* Python version: Python 2.7.10
* Operating System: MacOS

### Description
Exception in thread Thread-486:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysonofflan/discover.py", line 69, in probe_ip
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 151, in __init__
OSError: [Errno 24] Too many open files

### What I Did

```
pysonofflan discover
```

**Comment by beachhouse123** [comment]
Try increasing the ulimit from it's default value of 256

 e.g. ulimit -n 10000
