### ISSUE TITLE
ModuleNotFoundError - websockets.framing

### ISSUE THREAD

**Issue by Camaendir** [beveradb/pysonofflan#133]
* pySonoffLAN version: 0.3.0
* Python version: 3.8.5 and 3.9.1
* Operating System: Windows and WSL

### Description

Trying to work with _pysonofflan_ either through the given script or through the framework it throws the following `ModuleNotFoundError`.

```
File "python3.8/site-packages/pysonofflan/__init__.py", line 57, in <module> 
    from .client import SonoffLANModeClient
File "python3.8/site-packages/pysonofflan/client.py", line 11, in <module>   
    from websockets.framing import OP_CLOSE, parse_close, OP_PING, OP_PONG
ModuleNotFoundError: No module named 'websockets.framing
```

### What I Did

either
`from pysonofflan import *` in python
or 
`python -m pysonoff discover` in bash/cmd

I already tried reinstalling/restarting everything.

**Comment by freebeans** [comment]
According to the [websockets library changelog](https://websockets.readthedocs.io/en/stable/changelog.html#id5), `websockets.framing` is deprecated since version 9.0 which was released May 1st, 2021.

Maybe the author hasn't had the chance to fix it yet. Perhaps you can try installing an older version of the websockets library using virtualenv until it's fixed.

**Comment by beachhouse123** [comment]
I have this issue too using latest version of Websockets (9.1)

Marks-MBP:~ mark$ pysonofflan
Traceback (most recent call last):
  File "/usr/local/bin/pysonofflan", line 5, in <module>
    from pysonofflan.cli import cli
  File "/usr/local/lib/python3.9/site-packages/pysonofflan/__init__.py", line 57, in <module>
    from .client import SonoffLANModeClient
  File "/usr/local/lib/python3.9/site-packages/pysonofflan/client.py", line 11, in <module>
    from websockets.framing import OP_CLOSE, parse_close, OP_PING, OP_PONG
ModuleNotFoundError: No module named 'websockets.framing'

Reverting to Websockets 8.1 does not work due to other issues.

**Comment by beachhouse123** [comment]
I removed the import from websockets.framing on the basis of the changelog  for Websockets here:

https://websockets.readthedocs.io/en/stable/changelog.html#id2. The websockets.framing API have been deprecated-"The framing, handshake, headers, http, and uri modules in the websockets package are deprecated. These modules provided low-level APIs for reuse by other WebSocket implementations, but that never happened. Keeping these APIs public makes it more difficult to improve websockets for no actual benefit." 

The terms that would be imported in client.py at line 11 are resolved in pyc files in /usr/local/lib/python3.9/site-packages/websockets/__pycache__

I have reverted all the way back to 6 with the same issue so I think the issue is likely to be a problem in my environment but I don't know why. I've compared my output with that expected and the resolution of IP address to device is not happening when pysonofflan hangs. In addition I now have some additional error messages after timeouts which give a clue:

pysonofflan discover
2021-07-23 00:36:06,742 - info: Attempting to discover Sonoff LAN Mode devices on the local network, please wait...
2021-07-23 00:36:07,388 - info: Found Sonoff LAN Mode device at IP 192.168.0.10
$ pysonofflan --host 192.168.0.10 listen
2021-07-23 00:36:27,815 - info: Initialising SonoffSwitch with host 192.168.0.10
2021-07-23 00:41:28,420 - error: SonoffLANModeClient connection failed: Malformed HTTP message
2021-07-23 00:41:28,421 - warning: Unable to connect: Malformed HTTP message

-----------

OK, this is my error. The Sonoff S26 device I am using is running r3.5.1 firmware which is incompatible with Pysonofflan. I don't have a device with V2 firmware on to test the above changes with.

**Comment by beveradb** [comment]
> From the commits, issues and pull request's dates, this project seems to be unmaintained. It look like the correct fix for the issue could take some time to be released and perhaps reverting to the older version of the library is the best choice.

Hey, just wanted to say sorry for this, you're right in that I'm personally not doing any proactive efforts on this repo anymore as I don't actually have a sonoff with original firmware myself anymore (mine are all ESPHome or Tasmota now) so have no incentive to work on it.

However, if anyone wants to be given maintainer permissions I'm more than happy to grant that, or if anyone submits a PR which just needs to be merged/released I'm happy to do that if someone tags me specifically asking me to do that - as long as there's an understanding that I can't test it myself! 😄
